# Generated by Django 4.2.24 on 2025-09-14 15:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('primary_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('template_key', models.CharField(default='layout-1', max_length=64)),
                ('status', models.CharField(choices=[('active', 'active'), ('paused', 'paused'), ('deleted', 'deleted')], default='active', max_length=16)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('banner', models.JSONField(blank=True, default=dict)),
                ('about', models.JSONField(blank=True, default=dict)),
                ('services', models.JSONField(blank=True, default=dict)),
                ('products', models.JSONField(blank=True, default=dict)),
                ('gallery', models.JSONField(blank=True, default=dict)),
                ('clients', models.JSONField(blank=True, default=dict)),
                ('team', models.JSONField(blank=True, default=dict)),
                ('faq', models.JSONField(blank=True, default=dict)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('content_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('razorpay', 'razorpay'), ('stripe', 'stripe'), ('manual', 'manual')], max_length=32)),
                ('provider_id', models.CharField(blank=True, max_length=191, null=True)),
                ('amount_inr', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('succeeded', 'succeeded'), ('pending', 'pending'), ('failed', 'failed'), ('refunded', 'refunded')], max_length=16)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sitesvc.website')),
            ],
        ),
    ]
