# Generated by Django 4.2.25 on 2025-11-07 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitesvc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvSites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('primary_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('template_key', models.CharField(default='layout-1', max_length=64)),
                ('status', models.CharField(choices=[('active', 'active'), ('paused', 'paused'), ('deleted', 'deleted')], default='active', max_length=16)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('content_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
