# Generated by Django 4.2.25 on 2025-11-07 04:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitesvc', '0002_cvsites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CvSites',
            new_name='CommingSoonSites',
        ),
    ]
