# Generated by Django 4.2.25 on 2025-11-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesvc', '0003_rename_cvsites_commingsoonsites'),
    ]

    operations = [
        migrations.AddField(
            model_name='commingsoonsites',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
