# Generated by Django 4.2.25 on 2025-11-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesvc', '0004_commingsoonsites_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='commingsoonsites',
            name='color_settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='color_settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
