# Generated by Django 4.2.25 on 2025-11-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesvc', '0005_commingsoonsites_color_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commingsoonsites',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='website',
            name='owner',
        ),
    ]
